### ISSUE TITLE
Add build instruction to README

### ISSUE THREAD

**Issue by csexton** [zph/go-infect#1]
Sorry, just getting started with Go. It may be obvious, but how do I build.

I tried something like this:

```
% make build
rm -f dist/*
go build -o dist/infect main.go; \
        GOARCH=amd64 GOOS=linux go build -o dist/infect.linux_amd64 main.go; \
        GOARCH=amd64 GOOS=freebsd go build -o dist/infect.freebsd_amd64 main.go; \
        go build -gcflags '-N' -o dist/infect.debug main.go;
main.go:4:2: cannot find package "github.com/zph/go-infect/infect" in any of:
    /usr/local/Cellar/go/1.1.1/src/pkg/github.com/zph/go-infect/infect (from $GOROOT)
    ($GOPATH not set)
main.go:4:2: cannot find package "github.com/zph/go-infect/infect" in any of:
    /usr/local/Cellar/go/1.1.1/src/pkg/github.com/zph/go-infect/infect (from $GOROOT)
    ($GOPATH not set)
main.go:4:2: cannot find package "github.com/zph/go-infect/infect" in any of:
    /usr/local/Cellar/go/1.1.1/src/pkg/github.com/zph/go-infect/infect (from $GOROOT)
    ($GOPATH not set)
main.go:4:2: cannot find package "github.com/zph/go-infect/infect" in any of:
    /usr/local/Cellar/go/1.1.1/src/pkg/github.com/zph/go-infect/infect (from $GOROOT)
    ($GOPATH not set)
make: *** [build] Error 1
```

**Comment by zph** [comment]
No worries, I'm still getting going w/ it too :+1:.

Try `go get github.com/zph/go-infect`, then try running command again.

**Comment by zph** [comment]
Failing that, I built it for those three systems and pushed it up to the repo.

```
dist/infect <- mac version
dist/infect.{other platforms}
```

**Comment by zph** [comment]
I don't really know the right way to do package management and `$GOPATH` management yet... so if you figure it out before me, I'm all ears ;).

**Comment by csexton** [comment]
Blindly running binaries and typing strange commands into my terminal. 

![image](https://cloud.githubusercontent.com/assets/16963/3239381/4d400b68-f10a-11e3-910c-35c6cc6344ab.png)

**Comment by zph** [comment]
Last thing, you can play with it without borking your real vim folder by:

`cp -a ~/.vim* ~/tmp/`

Then `export INFECT_DEBUG=true`

It'll act on your `~/tmp/.vimrc and ~/tmp/.vim/bundle` instead if INFECT_DEBUG=true is set :+1:

**Comment by csexton** [comment]
![image](https://cloud.githubusercontent.com/assets/16963/3239430/4727dd68-f10b-11e3-8034-a7aca2eddc0c.png)

**Comment by zph** [comment]
AMG.... awesome :+1: ... glad I didn't accidentally leave a `rm -rf --no-preserve-root /` in there!

It's a good start for `go-infect`.  And fun writing some crude golang in the process.

**Comment by csexton** [comment]
Now I just need to learn me more go and start helping :shipit:

**Comment by zph** [comment]
Omg this was ~4 yrs ago ^_^.

**Comment by csexton** [comment]
Those were a good 4 years (and 2 months)!
